name: Dimensify
version: 1.0.0
main: me.ifydev.dimensifyspigot.DimensifyMain
author: IfyDev

commands:
  dimensify:
    decsription: "Do things with dimensions"
    permission: dimensify.command.base
