name: Dimensify
version: 0.0.1
main: me.ifydev.dimensifyspigot.DimensifyMain
author: IfyDev

commands:
  dimensify:
    decsription: "Do things with dimensions"
    permission: dimensify.command.base
